name: Deploy Django Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Virtual Machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_DEPLOYMENT_HOST }}
        port: ${{ secrets.CI_DEPLOYMENT_PORT }}
        username: ${{ secrets.CI_RPI_USERNAME }}
        key: ${{ secrets.CI_RPI_SSH_KEY }}
        script: |
          # Navigate to the home directory or your desired parent directory
          cd ~

          # Attempt to navigate to the tally-light directory
          if [ -d "Tally-light" ]; then
            echo "Directory tally-light exists. Pulling the latest changes."
            cd Tally-light
            git pull
          else
            echo "Directory tally-light does not exist. Cloning the repository."
            git clone https://github.com/pam-param-pam/Tally-light.git
            cd Tally-light
          fi
          
          # Checkout the master branch
          git checkout master

          # Navigate to the relay directory
          cd relay

          # Create or update the .env file with the secrets
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "DEBUG=False" >> .env

          # Check if virtual environment exists; create if it doesn't
          if [ ! -d "venv" ]; then
            echo "Virtual environment not found, creating one."
            python3 -m venv venv
          fi
          
          # Activate virtual environment
          source venv/bin/activate
          
          # Upgrade pip to avoid potential issues
          pip install --upgrade pip
          
          # Install required packages
          pip install -r requirements.txt
          
          # Run daemon service
          sudo mv .env /etc/systemd/system/tally-light.env
          sudo cp tally-light.service /etc/systemd/system/tally-light.service

          sudo systemctl daemon-reload
          sudo systemctl restart tally-light
          sudo systemctl status tally-light
          
          # Optional: Check the status of the service
          sudo systemctl status tally-light
