name: Deploy Django Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Virtual Machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_DEPLOYMENT_HOST }}
        port: ${{ secrets.CI_DEPLOYMENT_PORT }}
        username: ${{ secrets.CI_RPI_USERNAME }}
        key: ${{ secrets.CI_RPI_SSH_KEY }}
        script: |
          # Navigate to the home directory or your desired parent directory
          cd ~

          # Attempt to navigate to the tally-light directory
          if [ -d "Tally-light" ]; then
            echo "Directory tally-light exists. Pulling the latest changes."
            cd Tally-light
            git pull
          else
            echo "Directory tally-light does not exist. Cloning the repository."
            git clone https://github.com/pam-param-pam/Tally-light.git
            cd Tally-light
          fi
          
          # Checkout the master branch
          git checkout master

          # Navigate to the relay directory
          cd relay

          # Create or update the .env file with the DJANGO_SECRET_KEY
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
          echo "DEBUG=false" > .env

          # Activate virtual environment
          source venv/bin/activate
          
          # Install required packages
          pip install -r requirements.txt
          
          # Run Django application
          nohup python manage.py runserver 0.0.0.0:9000 &
