name: Start Django Application

on:
  workflow_dispatch:

jobs:
  start-service:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Start Service via Cloudflare SSH
        uses: pam-param-pam/cloudflare-ssh-action@v1.0.0
        with:
          host: ${{ secrets.CI_DEPLOYMENT_HOST }}
          username: ${{ secrets.CI_RPI_USERNAME }}
          private-key: ${{ secrets.CI_RPI_SSH_KEY }}
          known-hosts: ${{ secrets.CI_RPI_SSH_KNOWN_HOSTS }}
          service-token-id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          service-token-secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
          command: |
            set -e
            sudo systemctl start tally-light
            sudo systemctl --no-pager --full status tally-light